services:
  
  db_python:
    image: postgres:15
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: python_database
    networks:
      - restaurant-network
    # volumes:
    #   - /postgres_data:/var/lib/postgresql/data

networks:
  restaurant-network:
    driver: bridge
    
volumes:
  postgres_data: