services:
  
  db_python:
    image: postgres:17.2
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: python_database
    networks:
      - restaurant-network
    volumes:
      - /postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db_python
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
    
volumes:
  postgres_data: