services:
  
  db_python:
    image: postgres:17.5-alpine3.21
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
    container_name: python_database
    networks:
      - restaurant-network
    volumes:
      - /postgres:/var/lib/postgresql/data

networks:
  restaurant-network:
    driver: bridge